# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fire2aamMainClass
                                 A QGIS plugin
 Simulate and analyze fires, under weather conditions, placing firebreaks, get stats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-02
        copyright            : (C) 2023 by fdo
        email                : fdo@bad
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Fire2aamMainClass class from file Fire2aamMainClass.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Fire2aamMainModule import Fire2aamMainClass
    return Fire2aamMainClass(iface)
